### ISSUE TITLE
Missing gradients in EMF files

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/libemf2svg#12]
In the generated SVGs we don't see any gradients.

<img width="498" alt="Screenshot 2021-07-12 at 7 43 02 PM" src="https://user-images.githubusercontent.com/11865/125281957-6f0a5d00-e349-11eb-8655-d9f0e0705854.png">

However, in the original Enterprise Architect PNGs, the gradients exist.

<img width="489" alt="Screenshot 2021-07-12 at 7 43 11 PM" src="https://user-images.githubusercontent.com/11865/125281979-73cf1100-e349-11eb-9aa5-ffe5b0c7b980.png">

We need to find out whether these gradients are actually missing from the EMFs or they got lost in the EMF=>SVG process.

Images:
[Primitives.zip](https://github.com/metanorma/libemf2svg/files/6801015/Primitives.zip)

**Comment by maxirmx** [comment]
I guess if it is related to #38 ....

**Comment by maxirmx** [comment]
@ronaldtse 
I made some tests as this issue is very close  to #38

- Attached emf file does not contain gradient brush
- If I create emf file with gradient brush it is correctly converted to svg

My guess is that gradient brush is very complex multilevel structure in emf file and EA does not (or did not) generate it. So the export gradient to png but not to emf.

I suggest we close this issue.

**Comment by ronaldtse** [comment]
Thanks @maxirmx !
