### ISSUE TITLE
are you the new mantainers

### ISSUE THREAD

**Issue by Kreijstal** [metanorma/libemf2svg#37]
are you mantainers?
if you are you should create a new issue upstream telling everyone to move here

**Comment by maxirmx** [comment]
Hi, @Kreijstal
This library is used in [metanorma](https://www.metanorma.org/) project but there are many other abandoned libraries like this one that are used there. Not sure if we are the 'real' maintainers, though    
@ronaldtse, what would you say ?

**Comment by maxirmx** [comment]
https://github.com/kakwa/libemf2svg/issues/46

**Comment by ronaldtse** [comment]
Thanks @maxirmx ! 

@Kreijstal as with open source we thank the original implementation and this is a fork moving forward since we continue our usage of the implementation. 

We are happy to maintain this as a modern fork or any other role as long as we can continue using it on modern platforms satisfying our needs.
