### ISSUE TITLE
Alignment of EMF output and PNG output for Enterprise Architect diagram

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/libemf2svg#5]
These are diagrams from ISO 19170-1, extracted from the ISO/TC 211 Harmonized Models set.

Every diagram comes in a pair of PNG and EMF. We want the SVG output to align with PNG.

[diagram-tests.zip](https://github.com/metanorma/libemf2svg/files/6714283/diagram-tests.zip)

**Comment by maxirmx** [comment]
EMF to SVG conversion requires mapping of coordinates. 
All files included in libemf2svg test sets contain explicit mapping control statements that are converted to SVG/CSS transforms
The files generated by Enterprise Architect do not contain such control statements. However, those files use coordinate systems 
that cannot be applied to SVG directly because of negative positioning so some transforms are required.

By default libemf2svg (and libqemf and others) generate translate statements, i.e. shift images 
For example,  if EMF image is bounded by  left:1, top:-517, right: 473, bottom: 10  
then transform is:   _(Xsvg, Ysvg) = (Xemf - left, Yemf - top)_

The PNG output uses mirroring (_Xsvg, Ysvg) = (Xemf, -1 * Yemf)_ with some additional shift that is not yet fully discovered.

It is possible to implement transform that will be compatible with Enterprise Architect. However it is not clear whether it will break conversion of files generated by other tools if such files do not contain explicit transforms.

**Comment by maxirmx** [comment]
"Geometry-wise" the best approach is to implement the folowing:
_if top>0 && bottom > 0    then transform=none
else if  top<bottom then transform = shift 
else transform = mirror_  
But it still does not exclude an option to break some legacy conversion


The other option is to have command-line switch and library parameter that will turn on Enterprise Architect comaptibility

**Comment by ronaldtse** [comment]
@maxirmx all I know is that on Windows, these EMF files display property in Word. So if we are able to mimic this behavior then it should be fine. Let's try the suggested approach.

**Comment by ronaldtse** [comment]
I was told that the Windows generated EMF files work -- the ones generated on Mac using CrossOver doesn't. That is very strange...

**Comment by ronaldtse** [comment]
Apparently Enterprise Architect and its usage of GDI+ creates issues via Wine emulation, since 2016:
https://sparxsystems.com/forums/smf/index.php/topic,37405.0.html

While Enterprise Architect claims you can disable GDI+ in the user guide of v15:
https://www.sparxsystems.com.au/enterprise_architect_user_guide/15.1/user_interface/diagram_appearance.html
<img width="833" alt="Screenshot 2021-06-29 at 11 42 54 AM" src="https://user-images.githubusercontent.com/11865/123734046-30978b80-d8cf-11eb-9587-af60340dad7d.png">

But on my EA 15.1 (latest is 15.2) there is no such option:
<img width="827" alt="image" src="https://user-images.githubusercontent.com/11865/123733953-03e37400-d8cf-11eb-874d-03f36e477e81.png">
